name: sheild1
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev
publish_to: 'none'

# Version and build number
version: 1.0.0+1

# Define the SDK version
environment:
  sdk: ^3.6.2

# Project dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter-specific settings
flutter:
  uses-material-design: true

  # Assets section - Ensure the file exists in the "assets" folder
  assets:
    - assets\image.jpg